/* Generated by Yosys 0.58+86 (git sha1 3b9f06c13, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

(* src = "booth_controller.v:3.1-117.10" *)
module booth_controller(clk, start, q0, qm1, ldA, clrA, sft, ldQ, clrQ, clrff, ldM, addsub, done);
  (* src = "booth_controller.v:4.17-4.20" *)
  input clk;
  wire clk;
  (* src = "booth_controller.v:5.17-5.22" *)
  input start;
  wire start;
  (* src = "booth_controller.v:6.17-6.19" *)
  input q0;
  wire q0;
  (* src = "booth_controller.v:7.17-7.20" *)
  input qm1;
  wire qm1;
  (* src = "booth_controller.v:8.16-8.19" *)
  output ldA;
  reg ldA;
  (* src = "booth_controller.v:9.16-9.20" *)
  output clrA;
  reg clrA;
  (* src = "booth_controller.v:10.16-10.19" *)
  output sft;
  reg sft;
  (* src = "booth_controller.v:11.16-11.19" *)
  output ldQ;
  reg ldQ;
  (* src = "booth_controller.v:12.16-12.20" *)
  output clrQ;
  wire clrQ;
  (* src = "booth_controller.v:13.16-13.21" *)
  output clrff;
  wire clrff;
  (* src = "booth_controller.v:14.16-14.19" *)
  output ldM;
  wire ldM;
  (* src = "booth_controller.v:15.16-15.22" *)
  output addsub;
  reg addsub;
  (* src = "booth_controller.v:16.16-16.20" *)
  output done;
  reg done;
  (* src = "booth_controller.v:37.5-115.8" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  (* force_downto = 32'd1 *)
  (* src = "booth_controller.v:103.30-103.39|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [5:0] _046_;
  (* force_downto = 32'd1 *)
  (* src = "booth_controller.v:106.16-106.16|booth_controller.v:49.9-114.16|/usr/local/bin/../share/yosys/techmap.v:591.28-591.35" *)
  (* unused_bits = "5 9 10 11" *)
  wire [17:0] _047_;
  (* force_downto = 32'd1 *)
  (* src = "booth_controller.v:106.16-106.16|booth_controller.v:49.9-114.16|/usr/local/bin/../share/yosys/techmap.v:581.22-581.23" *)
  (* unused_bits = "3" *)
  wire [5:0] _048_;
  (* force_downto = 32'd1 *)
  (* src = "booth_controller.v:106.16-106.16|booth_controller.v:49.9-114.16|/usr/local/bin/../share/yosys/techmap.v:583.21-583.22" *)
  wire [2:0] _049_;
  (* src = "booth_controller.v:19.15-19.20" *)
  reg [5:0] count;
  (* src = "booth_controller.v:20.15-20.20" *)
  reg [2:0] state = 3'h0;
  assign _046_[0] = ~count[0];
  assign _003_ = state[0] | ~(state[1]);
  assign _047_[4] = state[2] & ~(_003_);
  assign _046_[1] = ~(count[1] ^ count[0]);
  assign _004_ = ~count[2];
  assign _005_ = count[1] | count[0];
  assign _046_[2] = _005_ ^ _004_;
  assign _006_ = _004_ & ~(_005_);
  assign _046_[3] = _006_ ^ count[3];
  assign _007_ = ~count[4];
  assign _008_ = ~(count[3] | count[2]);
  assign _009_ = count[3] | count[2];
  assign _010_ = _005_ & ~(_009_);
  assign _011_ = _010_ | ~(_008_);
  assign _046_[4] = _011_ ^ _007_;
  assign _012_ = _007_ & ~(_011_);
  assign _046_[5] = _012_ ^ count[5];
  assign _013_ = state[1] | ~(state[0]);
  assign _000_ = state[2] & ~(_013_);
  assign _014_ = state[1] | state[0];
  assign _015_ = state[2] & ~(_014_);
  assign _047_[8] = _015_ | _000_;
  assign _016_ = _009_ | _005_;
  assign _017_ = count[5] | count[4];
  assign _018_ = _017_ | _016_;
  assign _019_ = ~state[2];
  assign _047_[13] = _019_ & ~(_003_);
  assign _002_ = _047_[4] ? _018_ : _047_[13];
  assign _020_ = ~(state[1] & state[0]);
  assign _048_[0] = state[2] & ~(_020_);
  assign _047_[16] = _019_ & ~(_013_);
  assign _021_ = _019_ & ~(_014_);
  assign _022_ = start | ~(_021_);
  assign _023_ = state[1] & ~(state[0]);
  assign _024_ = state[2] ? _020_ : _013_;
  assign _025_ = _024_ & ~(_023_);
  assign _026_ = _019_ & ~(_020_);
  assign _027_ = _026_ | _021_;
  assign _028_ = _027_ | _047_[8];
  assign _029_ = _025_ & ~(_028_);
  assign _001_ = _022_ & ~(_029_);
  assign _030_ = ~(_048_[0] | _047_[4]);
  assign _031_ = _026_ | _047_[8];
  assign _032_ = _030_ & ~(_031_);
  assign _033_ = _047_[16] | _047_[13];
  assign _034_ = _033_ | ~(_032_);
  assign _035_ = qm1 | ~(q0);
  assign _036_ = _026_ & ~(_035_);
  assign _037_ = _036_ | _047_[4];
  assign _038_ = ~(_037_ | _047_[13]);
  assign _049_[0] = ~(_038_ & _034_);
  assign _039_ = qm1 ^ q0;
  assign _040_ = _026_ & ~(_039_);
  assign _041_ = _040_ | _047_[8];
  assign _042_ = _041_ | _047_[4];
  assign _043_ = ~(_042_ | _033_);
  assign _049_[1] = _034_ & ~(_043_);
  assign _044_ = _018_ | ~(_047_[4]);
  assign _045_ = _044_ & ~(_031_);
  assign _049_[2] = _034_ & ~(_045_);
  (* src = "booth_controller.v:37.5-115.8" *)
  always @(posedge clk)
    if (_001_) state[0] <= _049_[0];
  (* src = "booth_controller.v:37.5-115.8" *)
  always @(posedge clk)
    if (_001_) state[1] <= _049_[1];
  (* src = "booth_controller.v:37.5-115.8" *)
  always @(posedge clk)
    if (_001_) state[2] <= _049_[2];
  (* src = "booth_controller.v:37.5-115.8" *)
  always @(posedge clk)
    if (_002_)
      if (!_047_[4]) count[0] <= 1'h0;
      else count[0] <= _046_[0];
  (* src = "booth_controller.v:37.5-115.8" *)
  always @(posedge clk)
    if (_002_)
      if (!_047_[4]) count[1] <= 1'h0;
      else count[1] <= _046_[1];
  (* src = "booth_controller.v:37.5-115.8" *)
  always @(posedge clk)
    if (_002_)
      if (!_047_[4]) count[2] <= 1'h0;
      else count[2] <= _046_[2];
  (* src = "booth_controller.v:37.5-115.8" *)
  always @(posedge clk)
    if (_002_)
      if (!_047_[4]) count[3] <= 1'h0;
      else count[3] <= _046_[3];
  (* src = "booth_controller.v:37.5-115.8" *)
  always @(posedge clk)
    if (_002_)
      if (!_047_[4]) count[4] <= 1'h1;
      else count[4] <= _046_[4];
  (* src = "booth_controller.v:37.5-115.8" *)
  always @(posedge clk)
    if (_002_)
      if (!_047_[4]) count[5] <= 1'h0;
      else count[5] <= _046_[5];
  (* src = "booth_controller.v:37.5-115.8" *)
  always @(posedge clk)
    ldA <= _047_[8];
  (* src = "booth_controller.v:37.5-115.8" *)
  always @(posedge clk)
    clrA <= _047_[16];
  (* src = "booth_controller.v:37.5-115.8" *)
  always @(posedge clk)
    sft <= _047_[4];
  (* src = "booth_controller.v:37.5-115.8" *)
  always @(posedge clk)
    ldQ <= _047_[13];
  (* src = "booth_controller.v:37.5-115.8" *)
  always @(posedge clk)
    addsub <= _000_;
  (* src = "booth_controller.v:37.5-115.8" *)
  always @(posedge clk)
    done <= _048_[0];
  assign { _047_[17], _047_[15:14], _047_[12], _047_[7:6], _047_[3:0] } = { 3'h0, _047_[13], _047_[8], 1'h0, _047_[4], 3'h0 };
  assign _048_[5:1] = { _047_[16], _047_[13], _047_[11], _047_[8], _047_[4] };
  assign clrQ = 1'h0;
  assign clrff = clrA;
  assign ldM = clrA;
endmodule

(* dynports =  1  *)
(* src = "booth_datapath.v:3.1-85.10" *)
module booth_datapath(clk, ldA, clrA, sft, ldQ, clrQ, clrff, ldM, addsub, data_in, q0, qm1, A_out, Q_out);
  (* src = "booth_datapath.v:4.30-4.33" *)
  input clk;
  wire clk;
  (* src = "booth_datapath.v:5.30-5.33" *)
  input ldA;
  wire ldA;
  (* src = "booth_datapath.v:6.30-6.34" *)
  input clrA;
  wire clrA;
  (* src = "booth_datapath.v:7.30-7.33" *)
  input sft;
  wire sft;
  (* src = "booth_datapath.v:8.30-8.33" *)
  input ldQ;
  wire ldQ;
  (* src = "booth_datapath.v:9.30-9.34" *)
  input clrQ;
  wire clrQ;
  (* src = "booth_datapath.v:10.30-10.35" *)
  input clrff;
  wire clrff;
  (* src = "booth_datapath.v:11.30-11.33" *)
  input ldM;
  wire ldM;
  (* src = "booth_datapath.v:12.30-12.36" *)
  input addsub;
  wire addsub;
  (* src = "booth_datapath.v:13.30-13.37" *)
  input [15:0] data_in;
  wire [15:0] data_in;
  (* src = "booth_datapath.v:14.30-14.32" *)
  output q0;
  wire q0;
  (* src = "booth_datapath.v:15.30-15.33" *)
  output qm1;
  wire qm1;
  (* src = "booth_datapath.v:16.32-16.37" *)
  output [15:0] A_out;
  wire [15:0] A_out;
  (* src = "booth_datapath.v:17.32-17.37" *)
  output [15:0] Q_out;
  wire [15:0] Q_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  (* src = "booth_datapath.v:21.24-21.25" *)
  reg [15:0] A = 16'h0000;
  (* src = "booth_datapath.v:23.24-23.25" *)
  reg [15:0] M = 16'h0000;
  (* src = "booth_datapath.v:22.24-22.25" *)
  reg [15:0] Q = 16'h0000;
  (* src = "booth_datapath.v:24.9-24.15" *)
  reg qm1_ff = 1'h0;
  assign _001_ = sft | ldA;
  assign _000_ = ldQ | sft;
  assign _002_ = ldQ ? data_in[0] : Q[1];
  assign _009_ = ldQ ? data_in[1] : Q[2];
  assign _010_ = ldQ ? data_in[2] : Q[3];
  assign _011_ = ldQ ? data_in[3] : Q[4];
  assign _012_ = ldQ ? data_in[4] : Q[5];
  assign _013_ = ldQ ? data_in[5] : Q[6];
  assign _014_ = ldQ ? data_in[6] : Q[7];
  assign _015_ = ldQ ? data_in[7] : Q[8];
  assign _016_ = ldQ ? data_in[8] : Q[9];
  assign _017_ = ldQ ? data_in[9] : Q[10];
  assign _003_ = ldQ ? data_in[10] : Q[11];
  assign _004_ = ldQ ? data_in[11] : Q[12];
  assign _005_ = ldQ ? data_in[12] : Q[13];
  assign _006_ = ldQ ? data_in[13] : Q[14];
  assign _007_ = ldQ ? data_in[14] : Q[15];
  assign _008_ = ldQ ? data_in[15] : A[0];
  assign _018_ = M[0] ^ A[0];
  assign _185_ = ldA ? _018_ : A[1];
  assign _019_ = ~M[1];
  assign _020_ = ~(M[0] ^ M[1]);
  assign _021_ = addsub ? _019_ : _020_;
  assign _022_ = _021_ ^ A[1];
  assign _023_ = M[0] & ~(A[0]);
  assign _024_ = ~(_023_ ^ _022_);
  assign _192_ = ldA ? _024_ : A[2];
  assign _025_ = ~A[2];
  assign _026_ = ~M[2];
  assign _027_ = ~(M[0] | M[1]);
  assign _028_ = _027_ ^ M[2];
  assign _029_ = addsub ? _026_ : _028_;
  assign _030_ = _029_ ^ _025_;
  assign _031_ = _021_ & A[1];
  assign _032_ = _022_ & ~(_023_);
  assign _033_ = _032_ | _031_;
  assign _034_ = ~(_033_ ^ _030_);
  assign _193_ = ldA ? _034_ : A[3];
  assign _035_ = ~M[3];
  assign _036_ = _027_ & ~(M[2]);
  assign _037_ = _036_ ^ M[3];
  assign _038_ = addsub ? _035_ : _037_;
  assign _039_ = ~(_038_ ^ A[3]);
  assign _040_ = ~(_029_ & A[2]);
  assign _041_ = _033_ & ~(_030_);
  assign _042_ = _040_ & ~(_041_);
  assign _043_ = _042_ ^ _039_;
  assign _194_ = ldA ? _043_ : A[4];
  assign _044_ = ~A[4];
  assign _045_ = ~M[4];
  assign _046_ = M[3] | M[2];
  assign _047_ = _027_ & ~(_046_);
  assign _048_ = _047_ ^ M[4];
  assign _049_ = addsub ? _045_ : _048_;
  assign _050_ = _049_ ^ _044_;
  assign _051_ = _038_ & A[3];
  assign _052_ = ~(_040_ | _039_);
  assign _053_ = _052_ | _051_;
  assign _054_ = _039_ | _030_;
  assign _055_ = _033_ & ~(_054_);
  assign _056_ = _055_ | _053_;
  assign _057_ = ~(_056_ ^ _050_);
  assign _195_ = ldA ? _057_ : A[5];
  assign _058_ = ~M[5];
  assign _059_ = _047_ & ~(M[4]);
  assign _060_ = _059_ ^ _058_;
  assign _061_ = addsub ? M[5] : _060_;
  assign _062_ = _061_ ^ A[5];
  assign _063_ = ~(_049_ & A[4]);
  assign _064_ = _056_ & ~(_050_);
  assign _065_ = _063_ & ~(_064_);
  assign _066_ = _065_ ^ _062_;
  assign _196_ = ldA ? _066_ : A[6];
  assign _067_ = ~M[6];
  assign _068_ = M[5] | M[4];
  assign _069_ = _047_ & ~(_068_);
  assign _070_ = _069_ ^ M[6];
  assign _071_ = addsub ? _067_ : _070_;
  assign _072_ = ~(_071_ ^ A[6]);
  assign _073_ = A[5] & ~(_061_);
  assign _074_ = ~(_063_ | _062_);
  assign _075_ = _074_ | _073_;
  assign _076_ = _062_ | _050_;
  assign _077_ = _076_ | ~(_056_);
  assign _078_ = _077_ & ~(_075_);
  assign _079_ = _078_ ^ _072_;
  assign _197_ = ldA ? _079_ : A[7];
  assign _080_ = ~M[7];
  assign _081_ = _069_ & ~(M[6]);
  assign _082_ = _081_ ^ _080_;
  assign _083_ = addsub ? M[7] : _082_;
  assign _084_ = _083_ ^ A[7];
  assign _085_ = ~(_071_ & A[6]);
  assign _086_ = ~(_078_ | _072_);
  assign _087_ = _085_ & ~(_086_);
  assign _088_ = _087_ ^ _084_;
  assign _198_ = ldA ? _088_ : A[8];
  assign _089_ = ~M[8];
  assign _090_ = M[7] | M[6];
  assign _091_ = _090_ | _068_;
  assign _092_ = _047_ & ~(_091_);
  assign _093_ = _092_ ^ M[8];
  assign _094_ = addsub ? _089_ : _093_;
  assign _095_ = ~(_094_ ^ A[8]);
  assign _096_ = A[7] & ~(_083_);
  assign _097_ = ~(_085_ | _084_);
  assign _098_ = ~(_097_ | _096_);
  assign _099_ = _084_ | _072_;
  assign _100_ = _075_ & ~(_099_);
  assign _101_ = _098_ & ~(_100_);
  assign _102_ = _099_ | _076_;
  assign _103_ = _056_ & ~(_102_);
  assign _104_ = _103_ | ~(_101_);
  assign _105_ = ~(_104_ ^ _095_);
  assign _199_ = ldA ? _105_ : A[9];
  assign _106_ = ~M[9];
  assign _107_ = _092_ & ~(M[8]);
  assign _108_ = _107_ ^ M[9];
  assign _109_ = addsub ? _106_ : _108_;
  assign _110_ = ~(_109_ ^ A[9]);
  assign _111_ = ~(_094_ & A[8]);
  assign _112_ = _104_ & ~(_095_);
  assign _113_ = _111_ & ~(_112_);
  assign _114_ = _113_ ^ _110_;
  assign _200_ = ldA ? _114_ : A[10];
  assign _115_ = ~M[10];
  assign _116_ = M[9] | M[8];
  assign _117_ = _092_ & ~(_116_);
  assign _118_ = _117_ ^ M[10];
  assign _119_ = addsub ? _115_ : _118_;
  assign _120_ = ~(_119_ ^ A[10]);
  assign _121_ = _109_ & A[9];
  assign _122_ = ~(_111_ | _110_);
  assign _123_ = _122_ | _121_;
  assign _124_ = _110_ | _095_;
  assign _125_ = _124_ | ~(_104_);
  assign _126_ = _125_ & ~(_123_);
  assign _127_ = _126_ ^ _120_;
  assign _186_ = ldA ? _127_ : A[11];
  assign _128_ = ~M[11];
  assign _129_ = _117_ & ~(M[10]);
  assign _130_ = _129_ ^ M[11];
  assign _131_ = addsub ? _128_ : _130_;
  assign _132_ = ~(_131_ ^ A[11]);
  assign _133_ = ~(_119_ & A[10]);
  assign _134_ = ~(_126_ | _120_);
  assign _135_ = _133_ & ~(_134_);
  assign _136_ = _135_ ^ _132_;
  assign _187_ = ldA ? _136_ : A[12];
  assign _137_ = ~M[12];
  assign _138_ = M[11] | M[10];
  assign _139_ = _138_ | _116_;
  assign _140_ = _092_ & ~(_139_);
  assign _141_ = _140_ ^ M[12];
  assign _142_ = addsub ? _137_ : _141_;
  assign _143_ = ~(_142_ ^ A[12]);
  assign _144_ = ~(_131_ & A[11]);
  assign _145_ = ~(_133_ | _132_);
  assign _146_ = _144_ & ~(_145_);
  assign _147_ = _132_ | _120_;
  assign _148_ = _123_ & ~(_147_);
  assign _149_ = _146_ & ~(_148_);
  assign _150_ = _147_ | _124_;
  assign _151_ = _104_ & ~(_150_);
  assign _152_ = _149_ & ~(_151_);
  assign _153_ = _152_ ^ _143_;
  assign _188_ = ldA ? _153_ : A[13];
  assign _154_ = ~M[13];
  assign _155_ = _140_ & ~(M[12]);
  assign _156_ = _155_ ^ M[13];
  assign _157_ = addsub ? _154_ : _156_;
  assign _158_ = ~(_157_ ^ A[13]);
  assign _159_ = ~(_142_ & A[12]);
  assign _160_ = ~(_152_ | _143_);
  assign _161_ = _159_ & ~(_160_);
  assign _162_ = _161_ ^ _158_;
  assign _189_ = ldA ? _162_ : A[14];
  assign _163_ = ~M[14];
  assign _164_ = M[13] | M[12];
  assign _165_ = _140_ & ~(_164_);
  assign _166_ = _165_ ^ M[14];
  assign _167_ = addsub ? _163_ : _166_;
  assign _168_ = ~(_167_ ^ A[14]);
  assign _169_ = ~(_157_ & A[13]);
  assign _170_ = ~(_159_ | _158_);
  assign _171_ = _169_ & ~(_170_);
  assign _172_ = _158_ | _143_;
  assign _173_ = ~(_172_ | _152_);
  assign _174_ = _171_ & ~(_173_);
  assign _175_ = _174_ ^ _168_;
  assign _190_ = ldA ? _175_ : A[15];
  assign _176_ = ~M[15];
  assign _177_ = _165_ & ~(M[14]);
  assign _178_ = _177_ ^ M[15];
  assign _179_ = addsub ? _176_ : _178_;
  assign _180_ = _179_ ^ A[15];
  assign _181_ = ~(_167_ & A[14]);
  assign _182_ = ~(_174_ | _168_);
  assign _183_ = _181_ & ~(_182_);
  assign _184_ = _183_ ^ _180_;
  assign _191_ = ldA & ~(_184_);
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[0] <= 1'h0;
    else if (_001_) A[0] <= _185_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[1] <= 1'h0;
    else if (_001_) A[1] <= _192_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[2] <= 1'h0;
    else if (_001_) A[2] <= _193_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[3] <= 1'h0;
    else if (_001_) A[3] <= _194_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[4] <= 1'h0;
    else if (_001_) A[4] <= _195_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[5] <= 1'h0;
    else if (_001_) A[5] <= _196_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[6] <= 1'h0;
    else if (_001_) A[6] <= _197_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[7] <= 1'h0;
    else if (_001_) A[7] <= _198_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[8] <= 1'h0;
    else if (_001_) A[8] <= _199_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[9] <= 1'h0;
    else if (_001_) A[9] <= _200_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[10] <= 1'h0;
    else if (_001_) A[10] <= _186_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[11] <= 1'h0;
    else if (_001_) A[11] <= _187_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[12] <= 1'h0;
    else if (_001_) A[12] <= _188_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[13] <= 1'h0;
    else if (_001_) A[13] <= _189_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[14] <= 1'h0;
    else if (_001_) A[14] <= _190_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[0] <= data_in[0];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[1] <= data_in[1];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[2] <= data_in[2];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[3] <= data_in[3];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[4] <= data_in[4];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[5] <= data_in[5];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[6] <= data_in[6];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[7] <= data_in[7];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[8] <= data_in[8];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[9] <= data_in[9];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[10] <= data_in[10];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[11] <= data_in[11];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[12] <= data_in[12];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[13] <= data_in[13];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[14] <= data_in[14];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (ldM) M[15] <= data_in[15];
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrA) A[15] <= 1'h0;
    else if (ldA) A[15] <= _191_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[0] <= 1'h0;
    else if (_000_) Q[0] <= _002_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[1] <= 1'h0;
    else if (_000_) Q[1] <= _009_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[2] <= 1'h0;
    else if (_000_) Q[2] <= _010_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[3] <= 1'h0;
    else if (_000_) Q[3] <= _011_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[4] <= 1'h0;
    else if (_000_) Q[4] <= _012_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[5] <= 1'h0;
    else if (_000_) Q[5] <= _013_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[6] <= 1'h0;
    else if (_000_) Q[6] <= _014_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[7] <= 1'h0;
    else if (_000_) Q[7] <= _015_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[8] <= 1'h0;
    else if (_000_) Q[8] <= _016_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[9] <= 1'h0;
    else if (_000_) Q[9] <= _017_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[10] <= 1'h0;
    else if (_000_) Q[10] <= _003_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[11] <= 1'h0;
    else if (_000_) Q[11] <= _004_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[12] <= 1'h0;
    else if (_000_) Q[12] <= _005_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[13] <= 1'h0;
    else if (_000_) Q[13] <= _006_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[14] <= 1'h0;
    else if (_000_) Q[14] <= _007_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrQ) Q[15] <= 1'h0;
    else if (_000_) Q[15] <= _008_;
  (* src = "booth_datapath.v:45.5-83.8" *)
  always @(posedge clk)
    if (clrff) qm1_ff <= 1'h0;
    else if (sft) qm1_ff <= Q[0];
  assign A_out = A;
  assign Q_out = Q;
  assign q0 = Q[0];
  assign qm1 = qm1_ff;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "booth_multiplier_full.v:3.1-65.10" *)
module booth_multiplier_full(clk, start, multiplicand, multiplier, product, done);
  (* src = "booth_multiplier_full.v:4.17-4.20" *)
  input clk;
  wire clk;
  (* src = "booth_multiplier_full.v:5.17-5.22" *)
  input start;
  wire start;
  (* src = "booth_multiplier_full.v:6.32-6.44" *)
  input [15:0] multiplicand;
  wire [15:0] multiplicand;
  (* src = "booth_multiplier_full.v:7.32-7.42" *)
  input [15:0] multiplier;
  wire [15:0] multiplier;
  (* src = "booth_multiplier_full.v:8.34-8.41" *)
  output [31:0] product;
  wire [31:0] product;
  (* src = "booth_multiplier_full.v:9.17-9.21" *)
  output done;
  wire done;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "booth_multiplier_full.v:20.25-20.30" *)
  wire [15:0] A_out;
  (* src = "booth_multiplier_full.v:20.32-20.37" *)
  wire [15:0] Q_out;
  (* src = "booth_multiplier_full.v:16.10-16.16" *)
  wire addsub;
  (* src = "booth_multiplier_full.v:13.15-13.19" *)
  wire clrA;
  (* src = "booth_multiplier_full.v:14.15-14.19" *)
  wire clrQ;
  (* src = "booth_multiplier_full.v:15.10-15.15" *)
  wire clrff;
  (* src = "booth_multiplier_full.v:23.18-23.26" *)
  wire [15:0] data_bus;
  (* src = "booth_multiplier_full.v:13.10-13.13" *)
  wire ldA;
  (* src = "booth_multiplier_full.v:15.17-15.20" *)
  wire ldM;
  (* src = "booth_multiplier_full.v:14.10-14.13" *)
  wire ldQ;
  (* src = "booth_multiplier_full.v:19.10-19.12" *)
  wire q0;
  (* src = "booth_multiplier_full.v:19.14-19.17" *)
  wire qm1;
  (* src = "booth_multiplier_full.v:13.21-13.24" *)
  wire sft;
  assign _00_ = ldQ & multiplier[0];
  assign data_bus[0] = ldM ? multiplicand[0] : _00_;
  assign _01_ = multiplier[1] & ldQ;
  assign data_bus[1] = ldM ? multiplicand[1] : _01_;
  assign _02_ = multiplier[2] & ldQ;
  assign data_bus[2] = ldM ? multiplicand[2] : _02_;
  assign _03_ = multiplier[3] & ldQ;
  assign data_bus[3] = ldM ? multiplicand[3] : _03_;
  assign _04_ = multiplier[4] & ldQ;
  assign data_bus[4] = ldM ? multiplicand[4] : _04_;
  assign _05_ = multiplier[5] & ldQ;
  assign data_bus[5] = ldM ? multiplicand[5] : _05_;
  assign _06_ = multiplier[6] & ldQ;
  assign data_bus[6] = ldM ? multiplicand[6] : _06_;
  assign _07_ = multiplier[7] & ldQ;
  assign data_bus[7] = ldM ? multiplicand[7] : _07_;
  assign _08_ = multiplier[8] & ldQ;
  assign data_bus[8] = ldM ? multiplicand[8] : _08_;
  assign _09_ = multiplier[9] & ldQ;
  assign data_bus[9] = ldM ? multiplicand[9] : _09_;
  assign _10_ = multiplier[10] & ldQ;
  assign data_bus[10] = ldM ? multiplicand[10] : _10_;
  assign _11_ = multiplier[11] & ldQ;
  assign data_bus[11] = ldM ? multiplicand[11] : _11_;
  assign _12_ = multiplier[12] & ldQ;
  assign data_bus[12] = ldM ? multiplicand[12] : _12_;
  assign _13_ = multiplier[13] & ldQ;
  assign data_bus[13] = ldM ? multiplicand[13] : _13_;
  assign _14_ = multiplier[14] & ldQ;
  assign data_bus[14] = ldM ? multiplicand[14] : _14_;
  assign _15_ = multiplier[15] & ldQ;
  assign data_bus[15] = ldM ? multiplicand[15] : _15_;
  (* module_not_derived = 32'd1 *)
  (* src = "booth_multiplier_full.v:47.22-61.6" *)
  booth_controller CTRL (
    .addsub(addsub),
    .clk(clk),
    .clrA(clrA),
    .clrQ(clrQ),
    .clrff(clrff),
    .done(done),
    .ldA(ldA),
    .ldM(ldM),
    .ldQ(ldQ),
    .q0(q0),
    .qm1(qm1),
    .sft(sft),
    .start(start)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "booth_multiplier_full.v:29.20-44.6" *)
  booth_datapath DP (
    .A_out(A_out),
    .Q_out(Q_out),
    .addsub(addsub),
    .clk(clk),
    .clrA(clrA),
    .clrQ(clrQ),
    .clrff(clrff),
    .data_in(data_bus),
    .ldA(ldA),
    .ldM(ldM),
    .ldQ(ldQ),
    .q0(q0),
    .qm1(qm1),
    .sft(sft)
  );
  assign product = { A_out, Q_out };
endmodule
